/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "main.h"

#include <stdint.h>
#include <stdio.h>
#include "scheduler.h"
#include "tasks.h"

int main(void)
{
	void (*task_handlers[TASKS_MAX_NUM])() = {idle_task, task0, task1, task2};
	//TODO: change to malloc
	scheduler_init(task_handlers, 4);
}
